// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hoop.Context;

#nullable disable

namespace hoop_2.Migrations
{
    [DbContext(typeof(hoopContext))]
    [Migration("20231127121413_MigracaoPelada")]
    partial class MigracaoPelada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hoop.Model.Jogador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Estrelas")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("PeladaID")
                        .HasColumnType("integer");

                    b.Property<string>("Posicao")
                        .HasColumnType("text");

                    b.Property<int?>("TimeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("PeladaID");

                    b.HasIndex("TimeID");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("hoop.Model.Pelada", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Duracao")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dataPelada")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.ToTable("Peladas");
                });

            modelBuilder.Entity("hoop.Model.Time", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("PeladaID")
                        .HasColumnType("integer");

                    b.Property<int>("numeroJogadores")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("PeladaID");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("hoop.Model.Jogador", b =>
                {
                    b.HasOne("hoop.Model.Pelada", null)
                        .WithMany("Jogadores")
                        .HasForeignKey("PeladaID");

                    b.HasOne("hoop.Model.Time", null)
                        .WithMany("Jogador")
                        .HasForeignKey("TimeID");
                });

            modelBuilder.Entity("hoop.Model.Time", b =>
                {
                    b.HasOne("hoop.Model.Pelada", null)
                        .WithMany("Times")
                        .HasForeignKey("PeladaID");
                });

            modelBuilder.Entity("hoop.Model.Pelada", b =>
                {
                    b.Navigation("Jogadores");

                    b.Navigation("Times");
                });

            modelBuilder.Entity("hoop.Model.Time", b =>
                {
                    b.Navigation("Jogador");
                });
#pragma warning restore 612, 618
        }
    }
}
